# Generated by Django 3.2 on 2021-04-30 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('serial_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('smartphone_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_number_id', to='shop.smartphone')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('theft', models.CharField(default='no', max_length=3)),
                ('is_accepted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='shop.purchase')),
            ],
        ),
    ]
