# Generated by Django 3.2.1 on 2021-05-06 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('serial_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=20)),
                ('smartphone_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('serial_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('laptop_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.laptop')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseAutomobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.automobile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('theft', models.CharField(default='no', max_length=3)),
                ('is_accepted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.purchaselaptop')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAutomobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('theft', models.CharField(default='no', max_length=3)),
                ('is_accepted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.purchaseautomobile')),
            ],
        ),
    ]
