# Generated by Django 3.2.1 on 2021-05-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_automobile_claimautomobile_claimlaptop_laptop_purchaseautomobile_purchaselaptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobile',
            old_name='smartphone_img',
            new_name='automobile_img',
        ),
    ]
