# Generated by Django 3.2.1 on 2021-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_claimlaptop_is_repairable'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_repairable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimautomobile',
            name='is_repairable',
            field=models.BooleanField(default=False),
        ),
    ]
