# Generated by Django 3.2.1 on 2021-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210506_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimautomobile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
