# Generated by Django 3.2.1 on 2021-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_claimautomobile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimlaptop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
